name: JavaScript
main: de.eldoria.javascript.JavaScript
version: 1.0
description: JavaScript Engine for Servers on Java 15 or higher.
api-version: 1.13
authors:
  - OpenJDK
  - GraalVM
  - Hadde
load: STARTUP

commands:
  js:
    aliases:
      - nashorn
      - eval
      - graal
    permission: javascript.eval
    description: Evaluate some JS.

permissions:
  javascript.eval:
    default: op
